export enum DocumentRole {
  SENDER = 'SENDER',
  BENEFICIARY = 'BENEFICIARY',
  STUDENT = 'STUDENT',
  ORDER = 'ORDER'
}

export enum DocumentType {
  PAN = 'PAN',
  AADHAR_FRONT = 'AADHAR_FRONT',
  AADHAR_BACK = 'AADHAR_BACK',
  PASSPORT_FRONT = 'PASSPORT_FRONT',
  PASSPORT_BACK = 'PASSPORT_BACK',
  UNIVERSITY_FEE_RECEIPT = 'UNIVERSITY_FEE_RECEIPT',
  LOAN_SANCTION_LETTER = 'LOAN_SANCTION_LETTER',
  UNIVERSITY_OFFER_LETTER = 'UNIVERSITY_OFFER_LETTER',
  OTHER = 'OTHER'
} 